### POST request to create new patient entity
POST http://localhost:4004/api/patients
Content-Type: application/json

{
  "name": "Kafka Test 1",
  "email": "kafkatest1@gamil.com",
  "address": "591 New York",
  "dateOfBirth": "2002-04-22",
  "registeredDate": "2025-07-05"
}

###