### POST request to create new patient entity
POST http://localhost:4000/patients
Content-Type: application/json

{
  "name": "Ankit Kumar",
  "email": "ankit123@gamil.com",
  "address": "591 New York",
  "dateOfBirth": "2002-04-22",
  "registeredDate": "2025-07-05"
}

###