### PUT request to update an existing patient
PUT http://localhost:4004/api/patients/123e4567-e89b-12d3-a456-426614174000
Content-Type: application/json

{
  "name": "Praveen Kumar",
  "email": "praveen123@gamil.com",
  "address": "591 New York",
  "dateOfBirth": "2002-04-22"
}

###